### ISSUE TITLE
GtestRunner - support before/after

### ISSUE THREAD

**Issue by polishcode** [DanAlbert/ndk-app-template#12]
Not sure this is the correct tracker, please redirect if not.

In some gtest scenarios I need to initialize java objects with current Android context before accessing them from C++.
An ideal solution (cleanest one) would be to support junit's @Before/@After annotations in GtestRunner.
Of course, one could perform initialization from C++, but that requires additional glue code and hides the main objective.
Is there a timely chance for GtestRunner to support that functionality?
Thanks a ton!

**Comment by DanAlbert** [comment]
It's not, this is just a sample. androidx is where the implementation comes from. http://b.android.com.
