### ISSUE TITLE
GtestRunner - support multiple test classes

### ISSUE THREAD

**Issue by polishcode** [DanAlbert/ndk-app-template#13]
Problem: a singleton instance of GtestRunner is the only entrance to ALL gtest test cases. Having hundreds of those, there is currently no flexibility in running a single one for e.g. debugging. The only way is to modify simultaneously CMakeLists.txt and source code to comment out all tests apart from the one we need to work on.

One possible (not ideal though) solution would be to allow multiple GtestRunner definitions that would work with multiple test libraries, e.g. each library for a subset of tests.

If there is a simpler approach please share @DanAlbert.
Thank you.

**Comment by DanAlbert** [comment]
You'd need to file an FR against androidx. This is just a sample.
