### ISSUE TITLE
native debugging does not work for tests in library module type

### ISSUE THREAD

**Issue by polishcode** [DanAlbert/ndk-app-template#14]
Running gtest-based tests both with and without native debugger works only for application module type.
When the module is of library type, debugger cannot attach to the native code.

Repro:
In build.gradle of app:
1. chane id 'com.android.application' -> id 'com.android.library'
2. comment out applicationId "com.example.myapplication"
3. try to run NativeTests with debugger

Result: 
Depending on version of gradle, AGP etc. sth like:
> Task :app:connectedDebugAndroidTest
Starting 0 tests on Pixel 6a - 13

or

> Task :nativelib:connectedDebugAndroidTest FAILED
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
48 actionable tasks: 3 executed, 45 up-to-date
Test run failed to complete. Instrumentation run failed due to Process crashed.
FAILURE: Build failed with an exception.
What went wrong:
Execution failed for task ':nativelib:connectedDebugAndroidTest'.

Expected behaviour: would be great to not be forced to add app boilerplate code (manifest, activity etc.) to strictly library-like modules to enable debugging. On the other hand - the price of that code is not too high, so overall prio is low.

**Comment by DanAlbert** [comment]
You need to file an Android Studio bug. None of the debugger is implemented here.

**Comment by polishcode** [comment]
https://issuetracker.google.com/u/1/issues/291659600
